### PR TITLE
Make sine_lut a u16[] to fix build errors (-Wnarrowing) on some machines

### PR DESCRIPTION
**Pull request by flerovii**
Compiling gbe-plus gave me a -Wnarrowing error on Arch Linux when compiling. 
Therefore I decided to fix it myself and create a pull request.

Kind Regards,
flerovium

### CODE REVIEW

**Comment by shonumi** [comment]
Thanks for the PR! Unfortunately, you're working on code I'm going to make obsolete soon. The thing is, I don't like having such a large sine table declared like that. I'd much rather have a function that dynamically calculates the table and stores it into a vector instead of copy+pasting code from VBA-M. I just need to pinpoint exactly how the sine table from the GBA BIOS is calculated, and that's something I'm working on atm.

**Comment by fredericmeyer** [comment]
No problem! Calculating tables dynamically is always a good idea when it only has to be once. I suggest you to disassemble the GBA BIOS with IDA Pro. It's a very convient way of reverse engineering stuff!

**Comment by shonumi** [comment]
The GBA BIOS has the table hardcoded at a certain address. It's there, but it's not clear how the exact values were calculated. For example, when I do it by hand (with KCalc to convert it into hexadecimal) the values are slightly off. They may have done some rounding when they made the BIOS. I'd like to find out one way or another.

BTW, I see you're working on NDS emulation too. Good luck ;)

**Comment by fredericmeyer** [comment]
Thanks! Still have to do a lot of information gathering though. Is it me or is GBATEK sometimes a little bit unclear regarding DS specific stuff?  I ported my ARM interpreter from C++ to C and I plan to add GBA emulation to the NDS emulator sooner or later but currently I'm a little bit sick of GBA and find NDS to be more interesting to work on :) Are you active on any specific IRC by chance? 
About the sine_lut problem, maybe I'll have a look into it too if I have the time.

**Comment by fredericmeyer** [comment]
I think I found the solution to the sine_lut generation problem hehe ;)

I wrote this small application in C which prints all the values from 0 to 255. What it basically does is rouding down the values from 0 to Pi and after that it rounds them up.
`#include <math.h>
#include <stdio.h>
#include <stdint.h>

#define PI 3.14159265
#define RATIO ((2*PI)/256)
#define PEEK 0x4000

void main()
{
    for (int i = 0; i < 256; i++) {
        double val = sin(i * RATIO) * PEEK;
        uint16_t xval;
        if (i < 129) {
            xval = (uint16_t)floor(val);
        } else {
            xval = (uint16_t)ceil(val);
        }
        printf("%x\n", xval);
    }
}
`
Since sine is between Pi to 2Pi the same as between 0 to Pi but just inverted we can also
do the following:
`#include <math.h>
#include <stdio.h>
#include <stdint.h>

#define PI 3.14159265
#define RATIO ((2*PI)/256)
#define PEEK 0x4000

void main()
{
    uint16_t sine_lut[256];
    for (int i = 0; i < 256; i++) {
        if (i < 128) {
            sine_lut[i] = floor(sin(i * RATIO) * PEEK);
        } else {
            sine_lut[i] = sine_lut[i - 128] * -1;
        }
        printf("%x\n", sine_lut[i]);
    }
}
`
In fact I think this is more or less how Nintendo generated the table and where the flooring and ceiling comes from since floor(i)*-1 should do the same as ceil(i*-1) if I'm not mistaken.

**Pull request closed without merging**
